$(document).ready(function(){
    $("#design").click(function(){
        $("#des").hide();
        $(".design").toggle();
        $("#design").toggle();
     });
    $("#development").click(function(){
        $("#dev").hide();
        $(".development").toggle();
        $("#development").toggle();
    });
    $("#product").click(function(){
        $("#mgt").hide();
        $(".product").toggle();
        $("#product").toggle();
    });
});
